### ISSUE TITLE
Chapter 04 - Composer error

### ISSUE THREAD

**Issue by bhavers** [rddill-IBM/ZeroToBlockchain#4] opened 2017-11-08 08:29 UTC
Bill, when i import the network in Composer and click "Connect now" i get the following error in the browser:

An error occurred 
t: Participant 'org.hyperledger.composer.system.NetworkAdmin#admin' does not have 'READ' access to resource 'org.hyperledger.composer.system.Network#zerotoblockchain-network@0.1.6'

The permissions.acl was unchanged:

/**
 * Access control rules for mynetwork
 */
rule Default {
    description: "Allow all participants access to all resources"
    participant: "ANY"
    operation: ALL
    resource: "org.acme.Z2BTestNetwork.*"
    action: ALLOW

Any clue what might be causing this?

**Comment by rddill-IBM** [comment] 2017-11-08 17:12
Yes, i know exactly what's causing this problem. In short it's the incompatibility between V0.13 and V0.14 of hyperledger composer. I'll post a fix to this shortly.

**Comment by rddill-IBM** [comment] 2017-11-08 18:09
This bug will remain open for a few days. During that time, composer playground will not be able to install the business networks we create in this tutorial. Resolving this requires updating the entire tutorial to hyperledger-composer V0.14. The Composer team acknowledges that this is a breaking upgrade and requires rework on all business networks created prior to V0.14. This issue will be closed when I release the V0.14 upgrade in a few days. Other than using composer-playground (Chapter 3 only), all other parts of this tutorial continue to operate correctly.

**Comment by rddill-IBM** [comment] 2017-11-13 14:10
The tutorial was updated on Friday to Version V1.1, specifically to resolve this issue by integrating support for V0.14 of Hyplerledger Composer. We were previously on V0.13, and this version difference was the root cause of the problem you encountered. Please let me know if you have nay further difficulty using Playground.

**Closed by rddill-IBM** 2017-11-13 14:10 UTC
